# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T08:44:51+00:00

from __future__ import annotations

from typing import List, Optional

from pydantic import BaseModel, ConfigDict


class Continent(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    code: Optional[str] = None
    name: Optional[str] = None


class Country(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    code: Optional[str] = None
    name: Optional[str] = None


class Isp(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: Optional[int] = None
    name: Optional[str] = None


class Subdivision(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    code: Optional[str] = None
    name: Optional[str] = None


class Timings(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    connectTime: Optional[float] = None
    firstByteTime: Optional[float] = None
    responseTime: Optional[float] = None


class Location(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    accuracyRadius: Optional[int] = None
    cityName: Optional[str] = None
    continent: Optional[Continent] = None
    country: Optional[Country] = None
    latitude: Optional[float] = None
    longitude: Optional[float] = None
    postalCode: Optional[str] = None
    subdivisions: Optional[List[Subdivision]] = None
    timezone: Optional[str] = None


class Proxy(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    accessType: Optional[str] = None
    address: Optional[str] = None
    isSsl: Optional[bool] = None
    isp: Optional[Isp] = None
    lastTested: Optional[str] = None
    location: Optional[Location] = None
    port: Optional[int] = None
    protocol: Optional[str] = None
    timings: Optional[Timings] = None
    uptime: Optional[float] = None
